apps/home/__init__.py
# -*- encoding: utf-8 -*-
from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
from apps.home import blueprint
from flask import render_template, request, jsonify
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from apps.helper_files.forms import CSVUploadForm
from apps.helper_files import label_generator
from markupsafe import Markup
import csv
import io

@blueprint.route('/index')
@login_required
def index():

    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500

@blueprint.route('/monthly_data', methods=['GET'])
@login_required
def show_geotiff():
    # Read the GeoTIFF file
    geotiff_url = "https://test-implify-test.s3.eu-central-1.amazonaws.com/wc2.1_30s_tavg/con_1.png"

    return render_template('home/geo_tiff.html', img_url=geotiff_url)

@blueprint.route('/fetch-new-pic', methods=['GET'])
def update_geotiff():
    # Read the GeoTIFF file
    month = request.args.get('month')
    geotiff_url = "https://test-implify-test.s3.eu-central-1.amazonaws.com/wc2.1_30s_tavg/con_"+str(month)+".png"

    return jsonify({'image_url': geotiff_url})

@blueprint.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_csv():
    form = CSVUploadForm()
    if request.method == 'POST':
        if form.validate():
            csv_file = request.files['csv_file']

            if not csv_file:
                return render_template('home/page-no-data.html', error='No csv file selected.')

            reader = csv.DictReader(io.TextIOWrapper(csv_file, encoding='utf-8'))
            columns_to_select = form.column_names.data.split(',')

            # raise error
            if len(columns_to_select) != 3:
                return render_template('home/page-no-data.html', error='Need 3 variables to be selected (x-axis, y-axis and variable to select upon)')

            x_data_column_name = columns_to_select[0]
            y_data_column_name = columns_to_select[1]
            z_data_column_name = columns_to_select[2]
            sliced = form.slicer.data.split(',')
            sliced_comp = {}
            for slice_sub in sliced:
                try:
                    sliced_comp[slice_sub.split('=')[0]] = slice_sub.split('=')[1]
                except:
                    print("slicing failed")
            data_to_plot = {}

            # Check if user matches columns
            for row in reader:
                # build in check
                add_data = True
                for slice_key in sliced_comp:
                    if row[slice_key].lower().replace(" ", "") != sliced_comp[slice_key].lower().replace(" ", ""):
                        add_data = False
                if add_data:
                    if row[z_data_column_name] in data_to_plot:
                        sub_data = data_to_plot[row[z_data_column_name]]
                        sub_data[0].append(row[x_data_column_name])
                        sub_data[1].append(row[y_data_column_name])
                    else:
                        sub_data = [[row[x_data_column_name]], [row[y_data_column_name]]]

                    data_to_plot[row[z_data_column_name]] = sub_data

            # Process valid data
            label, label_gen = label_generator(data_to_plot)

            if len(data_to_plot) == 0:
                return render_template('home/page-no-data.html', error='No data based on your selection')

            return render_template('home/index.html',variables_selected=form.slicer.data,
                                   data_to_pass=data_to_plot[list(data_to_plot.keys())[0]]\
                                   , labels=Markup(label),label_gen= Markup(label_gen))
        else:
            return render_template('home/page-500.html')

    return render_template('home/upload.html', form=form)

@blueprint.route('/profile')
@login_required
def profile():
    return render_template('home/profile.html', username=current_user.username, email=current_user.email)

# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/home/geo_tiff.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <div class="content">
    <div class="row">

    <div class="card">
    <div class="card-body">
    <form>
      <div class="form-group">
        <label >Select Month</label>
        <select class="form-control" id="month-selector" onchange="monthChanged()">
          <option value="1" selected>1</option>
          <option value="2" >2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
          <option>6</option>
          <option>7</option>
          <option>8</option>
          <option>9</option>
          <option>10</option>
          <option>11</option>
          <option>12</option>
        </select>
      </div>
    </form>
    </div>
    </div>

      <div class="col-md-8">
            <img src="{{img_url}}" alt="Image" id="image">
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
 <script>
        function monthChanged() {
            const selectedMonth = document.getElementById('month-selector').value;
            fetch(`/fetch-new-pic?month=${selectedMonth}`)
                .then(response => response.json())
                .then(data => {
                    console.log(data);
                    const imageURL = data.image_url;
                    console.log(imageURL);
                    document.getElementById('image').src = imageURL;
                });
        }
    </script>
{% endblock javascripts %}

apps/templates/home/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card card-chart">
                    <div class="card-header ">
                        <div class="row">
                            <div class="col-sm-6 text-left">
                                <h5 class="card-category">Selected plot</h5>
                                <h2 class="card-title">{{variables_selected}}</h2>
                            </div>
                        </div>
                                <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                                    {{labels}}
                                </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="chart-area">
                            <canvas id="chartBig1"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
            <div class="col-md-12">
                <button onclick="window.location.href='{{ url_for('home_blueprint.upload_csv')}}'" class="btn btn-primary">Go back</button>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>

$(document).ready(function () {

    var chart_labels = [{% for item in data_to_pass[0] %} "{{item}}", {% endfor %}];
    var chart_data = [{% for item in data_to_pass[1] %} {{item}}, {% endfor %}];

   gradientChartOptionsConfigurationWithTooltipPurple = {
      maintainAspectRatio: false,
      legend: {
        display: false
      },

      tooltips: {
        backgroundColor: '#f5f5f5',
        titleFontColor: '#333',
        bodyFontColor: '#666',
        bodySpacing: 4,
        xPadding: 12,
        mode: "nearest",
        intersect: 0,
        position: "nearest"
      },
      responsive: true,
      scales: {
        yAxes: [{
          barPercentage: 1.6,
          gridLines: {
            drawBorder: false,
            color: 'rgba(29,140,248,0.0)',
            zeroLineColor: "transparent",
          },
          ticks: {
            suggestedMin: 60,
            suggestedMax: 125,
            padding: 20,
            fontColor: "#9a9a9a"
          }
        }],

        xAxes: [{
          barPercentage: 1.6,
          gridLines: {
            drawBorder: false,
            color: 'rgba(225,78,202,0.1)',
            zeroLineColor: "transparent",
          },
          ticks: {
            padding: 20,
            fontColor: "#9a9a9a"
          }
        }]
      }
    };


    var ctx = document.getElementById("chartBig1").getContext('2d');

    var gradientStroke = ctx.createLinearGradient(0, 230, 0, 50);

    gradientStroke.addColorStop(1, 'rgba(72,72,176,0.1)');
    gradientStroke.addColorStop(0.4, 'rgba(72,72,176,0.0)');
    gradientStroke.addColorStop(0, 'rgba(119,52,169,0)'); //purple colors
    var config = {
        type: 'line',
        data: {
            labels: chart_labels,
            datasets: [{
                label: "My First dataset",
                fill: true,
                backgroundColor: gradientStroke,
                borderColor: '#d346b1',
                borderWidth: 2,
                borderDash: [],
                borderDashOffset: 0.0,
                pointBackgroundColor: '#d346b1',
                pointBorderColor: 'rgba(255,255,255,0)',
                pointHoverBackgroundColor: '#d346b1',
                pointBorderWidth: 20,
                pointHoverRadius: 4,
                pointHoverBorderWidth: 15,
                pointRadius: 4,
                data: chart_data,
            }]
        },
        options: gradientChartOptionsConfigurationWithTooltipPurple
    };
    var myChartData = new Chart(ctx, config);
    {{label_gen}}
    });
</script>

{% endblock javascripts %}

apps/templates/home/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h4 class="title">Login to CT ADMIN</h4>
                        </div>
                        <div class="card-body px-5 py-3">
                            <form>
                                <div class="row">
                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                            <input type="text" class="form-control" placeholder="Username"
                                                    value="michael23">
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" placeholder="password"
                                                    value="example@gmail.com">
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-fill btn-primary">Login</button>
                            
                            <br /><br />

                            <p>
                                Don't have an account? <a href="/register.html" class="text-primary">Register</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 403 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                Error 403
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Access denied - Please contact support.
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                Error 404
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Page not found - Please contact support.
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 500 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                Error 500
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Server ERROR - Please contact support.
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-no-data.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 500 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                {{error}}
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Please try again
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/profile.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <div class="content">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h5 class="title">Profile</h5>
          </div>

          <div class="card-body">
            <div>

              {% if not current_user.email %}
              <div class="row">

                <div class="col-md-6 pr-md-1">

                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <p class="mb-0">
                        Please add an email address.
                    </p>
                  </div>

                </div>

              </div>
              {% endif %}

              <div class="row">

                <div class="col-md-6 pr-md-1">
                  <div class="form-group">
                    <label class="form-label {% if not current_user.email %} text-danger {% endif%}">Email Address</label>
                    <input type="email" name="email" class="form-control"
                    {% if current_user.email %} readonly {% endif %}
                     placeholder="Your email Here"
                     value="{% if current_user.email %} {{ current_user.email }} {% endif %}">
                     <section class="display-error-message">
                    </section>
                  </div>
                </div>

                <div class="col-md-6 pr-md-1">
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" value="{{current_user.username}}"  readonly>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

apps/templates/home/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h4 class="title">
                                Sign UP
                            </h4>
                        </div>
                        <div class="card-body px-5 py-3">
                            <form>
                                <div class="row">
                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                            <input type="text" class="form-control" placeholder="Username"
                                                    value="michael23">
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" class="form-control" placeholder="email"
                                                    value="example@gmail.com">
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" placeholder="password"
                                                    value="example@gmail.com">
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-fill btn-primary">Register</button>

                            <br /><br />
                            
                            <p>
                                Have an account? <a href="/login.html" class="text-primary">Login</a>
                            </p> 
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/upload.html
{% extends "layouts/base.html" %}

{% block title %} UI Icons {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <h1>CSV Upload</h1>

        <form action="{{ url_for('home_blueprint.upload_csv') }}" method="post" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <label for="csv_file">Choose a CSV file:</label>
            <input type="file" id="csv_file" class="file-input" name="csv_file">
            <div class="form-group">
                <label for="column_names">Enter column names to plot (1st will be x-axis, 2nd y-axis and 3rd to select variable)</label>
                <input type="text" id="column_names" class="form-control" name="column_names" placeholder="Year,Value,Variable">
            </div>
            <div class="form-group">
                <label for="column_names">Filter on following (column as key and variable as value, see example in placeholder):</label>
                <input type="text" id="slicer" class="form-control" name="slicer" placeholder="Region=ANZ,Item=AGR,Scenario=Base_cc70,Unit=mn USD">
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>

        {% if form.errors %}
            <ul>
                {% for error in form.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
  </div>
  </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}